### Jeff Muller Design Portfolio

title: Jeff Muller
description: UX Designer | Industrial Designer | Visual Designer

baseurl: "" # no baseurl for Firebase hosting
url: "https://jeffmullerdesign.com"
email: jeff@jeffmullerdesign.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "jeffmuller"
instagram: "designmeaportrait"
facebook: "#"
github: "#"
stackoverflow: "#"
researchgate: "#"
orcid: "#"
quora: "#"
bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics: UA-6862985-2

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - library.md
      - ultrasonic.md
      - tractor.md
      - autoivi.md
      - defjam.md
      - conference.md
      - ivi.md
      - cadet.md
      - underdog.md
      - voyager.md
      - rocket.md
      - hoops.md
      - football.md
      - viber.md
      - luekens.md
      - sos.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
